config/routes.rb
Rails.application.routes.draw do
  get 'cart/new'

  get 'cart/update'

  get 'cart/empty'

  get 'cart/add'

  get 'cart/checkout'

  resources :widgets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# this is just a regular ruby class, not an active record model
class Cart
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
# you may use the regular ruby object in models/cart.rb,
# and store it in the session like this session.cart = Cart.new
class CartController < ApplicationController
  def new
    session[:cart] = Cart.new
  end

  def update
  end

  def empty
  end

  def add
  end

  # cart should be totalled and paid for using the
  # services/payment_settlement_service.rb class
  def checkout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/cart/add.html.erb
<h1>Cart#add</h1>
<p>Find me in app/views/cart/add.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Cart#checkout</h1>
<p>Find me in app/views/cart/checkout.html.erb</p>

app/views/cart/create.html.erb
<h1>Cart#create</h1>
<p>Find me in app/views/cart/create.html.erb</p>

app/views/cart/empty.html.erb
<h1>Cart#empty</h1>
<p>Find me in app/views/cart/empty.html.erb</p>

app/views/cart/new.html.erb
<h1>Cart#new</h1>
<p>Find me in app/views/cart/new.html.erb</p>

app/views/cart/update.html.erb
<h1>Cart#update</h1>
<p>Find me in app/views/cart/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WidgetStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/widgets/_form.html.erb
<%= form_with(model: widget, local: true) do |form| %>
  <% if widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku, id: :widget_sku %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :widget_description %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.number_field :unit_price, id: :widget_unit_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Sku</th>
      <th>Description</th>
      <th>Unit price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.sku %></td>
        <td><%= widget.description %></td>
        <td><%= widget.unit_price %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form', widget: @widget %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sku:</strong>
  <%= @widget.sku %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @widget.unit_price %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>